name: CI/CD for chatio API

on:
  push:
    branches:
      - master  # This triggers the workflow on pushes to the master branch

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      # Step 1: Check out the code
      - name: Checkout code
        uses: actions/checkout@v3

      # Step 2: Deploy to VPS via SSH and use Docker
      - name: Deploy to VPS via SSH
        uses: appleboy/ssh-action@v0.1.5
        with:
          host: ${{ secrets.VPS_HOST }}
          username: ${{ secrets.VPS_USER }}
          key: ${{ secrets.VPS_SSH_KEY }}
          port: 22
          script: |
            # Go to the deployment path
            cd ..
            cd ${{ secrets.VPS_DEPLOY_PATH }}

            # Pull the latest changes from the master branch
            git pull origin master

            # Export environment variables from GitHub secrets
            export NODE_ENV=production
            export DATABASE_URL="mongodb://${{ secrets.MONGO_INITDB_ROOT_USERNAME }}:${{ secrets.MONGO_INITDB_ROOT_PASSWORD }}@mongo_db:27017/${{ secrets.MONGO_INITDB_DATABASE }}"
            export JWT_SECRET=${{ secrets.JWT_SECRET }}
            export PORT=${{ secrets.PORT }}

            # MongoDB authentication parameters from GitHub Secrets
            export MONGO_INITDB_ROOT_USERNAME=${{ secrets.MONGO_INITDB_ROOT_USERNAME }}
            export MONGO_INITDB_ROOT_PASSWORD=${{ secrets.MONGO_INITDB_ROOT_PASSWORD }}
            export MONGO_INITDB_DATABASE=${{ secrets.MONGO_INITDB_DATABASE }}

            # Stop existing containers
            # docker-compose down

            # Build Docker images with the latest changes
            docker-compose build

            # Run the new containers in detached mode
            docker-compose up -d
          debug: true
